services:
  - type: docker
    name: weragenda-n8n
    env: docker
    plan: free
    repo: https://github.com/faquant/n8n-render-weragenda
    dockerfilePath: null
    dockerComposePath: docker-compose.yml
    autoDeploy: false
