services:
  - type: web
    name: weragenda-n8n
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: false
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: weragenda123
      - key: N8N_ENCRYPTION_KEY
        value: weragendaencryption123
      - key: WEBHOOK_URL
        value: https://weragenda-n8n.onrender.com/
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: dpg-d130uibuibrs73fn6jq0-a
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: n8n_0ywz
      - key: DB_POSTGRESDB_USER
        value: n8n
      - key: DB_POSTGRESDB_PASSWORD
        value: gtRmblovTuoVqCDFfSd2pYK8u26R5MX5
      - key: N8N_RUNNERS_ENABLED
        value: "true"
